// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: currency.proto

package generated_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CurrencyClient is the client API for Currency service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CurrencyType, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CurrencyType, error)
	GetSupported(ctx context.Context, in *GetSupportedRequest, opts ...grpc.CallOption) (*GetSupportedResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*CurrencyType, error)
	SetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*CurrencyType, error)
	GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*RateType, error)
	SetRate(ctx context.Context, in *SetRateRequest, opts ...grpc.CallOption) (*RateType, error)
	ForceUpdateRate(ctx context.Context, in *ForceUpdateRateRequest, opts ...grpc.CallOption) (*RateType, error)
}

type currencyClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyClient(cc grpc.ClientConnInterface) CurrencyClient {
	return &currencyClient{cc}
}

func (c *currencyClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CurrencyType, error) {
	out := new(CurrencyType)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CurrencyType, error) {
	out := new(CurrencyType)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) GetSupported(ctx context.Context, in *GetSupportedRequest, opts ...grpc.CallOption) (*GetSupportedResponse, error) {
	out := new(GetSupportedResponse)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/GetSupported", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*CurrencyType, error) {
	out := new(CurrencyType)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) SetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*CurrencyType, error) {
	out := new(CurrencyType)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/SetEnabled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*RateType, error) {
	out := new(RateType)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/GetRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) SetRate(ctx context.Context, in *SetRateRequest, opts ...grpc.CallOption) (*RateType, error) {
	out := new(RateType)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/SetRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) ForceUpdateRate(ctx context.Context, in *ForceUpdateRateRequest, opts ...grpc.CallOption) (*RateType, error) {
	out := new(RateType)
	err := c.cc.Invoke(ctx, "/autobar.currency_service.Currency/ForceUpdateRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyServer is the server API for Currency service.
// All implementations must embed UnimplementedCurrencyServer
// for forward compatibility
type CurrencyServer interface {
	Create(context.Context, *CreateRequest) (*CurrencyType, error)
	Get(context.Context, *GetRequest) (*CurrencyType, error)
	GetSupported(context.Context, *GetSupportedRequest) (*GetSupportedResponse, error)
	Delete(context.Context, *DeleteRequest) (*CurrencyType, error)
	SetEnabled(context.Context, *SetEnabledRequest) (*CurrencyType, error)
	GetRate(context.Context, *GetRateRequest) (*RateType, error)
	SetRate(context.Context, *SetRateRequest) (*RateType, error)
	ForceUpdateRate(context.Context, *ForceUpdateRateRequest) (*RateType, error)
	mustEmbedUnimplementedCurrencyServer()
}

// UnimplementedCurrencyServer must be embedded to have forward compatible implementations.
type UnimplementedCurrencyServer struct {
}

func (UnimplementedCurrencyServer) Create(context.Context, *CreateRequest) (*CurrencyType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCurrencyServer) Get(context.Context, *GetRequest) (*CurrencyType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCurrencyServer) GetSupported(context.Context, *GetSupportedRequest) (*GetSupportedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupported not implemented")
}
func (UnimplementedCurrencyServer) Delete(context.Context, *DeleteRequest) (*CurrencyType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCurrencyServer) SetEnabled(context.Context, *SetEnabledRequest) (*CurrencyType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEnabled not implemented")
}
func (UnimplementedCurrencyServer) GetRate(context.Context, *GetRateRequest) (*RateType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedCurrencyServer) SetRate(context.Context, *SetRateRequest) (*RateType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRate not implemented")
}
func (UnimplementedCurrencyServer) ForceUpdateRate(context.Context, *ForceUpdateRateRequest) (*RateType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceUpdateRate not implemented")
}
func (UnimplementedCurrencyServer) mustEmbedUnimplementedCurrencyServer() {}

// UnsafeCurrencyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyServer will
// result in compilation errors.
type UnsafeCurrencyServer interface {
	mustEmbedUnimplementedCurrencyServer()
}

func RegisterCurrencyServer(s grpc.ServiceRegistrar, srv CurrencyServer) {
	s.RegisterService(&Currency_ServiceDesc, srv)
}

func _Currency_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_GetSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).GetSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/GetSupported",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).GetSupported(ctx, req.(*GetSupportedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_SetEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).SetEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/SetEnabled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).SetEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/GetRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).GetRate(ctx, req.(*GetRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_SetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).SetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/SetRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).SetRate(ctx, req.(*SetRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_ForceUpdateRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceUpdateRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).ForceUpdateRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autobar.currency_service.Currency/ForceUpdateRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).ForceUpdateRate(ctx, req.(*ForceUpdateRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Currency_ServiceDesc is the grpc.ServiceDesc for Currency service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Currency_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autobar.currency_service.Currency",
	HandlerType: (*CurrencyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Currency_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Currency_Get_Handler,
		},
		{
			MethodName: "GetSupported",
			Handler:    _Currency_GetSupported_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Currency_Delete_Handler,
		},
		{
			MethodName: "SetEnabled",
			Handler:    _Currency_SetEnabled_Handler,
		},
		{
			MethodName: "GetRate",
			Handler:    _Currency_GetRate_Handler,
		},
		{
			MethodName: "SetRate",
			Handler:    _Currency_SetRate_Handler,
		},
		{
			MethodName: "ForceUpdateRate",
			Handler:    _Currency_ForceUpdateRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currency.proto",
}
